version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elevate-backend
    env_file:
      - .env
    restart: always
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elevate-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
