version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elevate-backend
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elevate-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stoppedversion: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elevate-backend
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elevate-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped