user_profiles = [
    {
        "user_id": "user123",
        "name": "Alex Johnson",
        "email": "alex.johnson@company.com",
        "department": "Engineering",
        "role": "Senior Software Engineer",
        "skills": ["Python", "React", "FastAPI", "AWS", "Database Optimization", "Security"],
        "interests": ["Machine Learning", "DevOps", "Cybersecurity"],
        "experience": 5,
        "projects": ["Customer Portal", "Analytics Dashboard", "Payment System"],
        "desired_skills": ["Kubernetes", "Machine Learning", "Leadership"],
        "manager_id": "manager456",
        "joined_date": "2020-03-15"
    },
    {
        "user_id": "user234",
        "name": "Jamie Smith",
        "email": "jamie.smith@company.com",
        "department": "Engineering",
        "role": "DevOps Engineer",
        "skills": ["Kubernetes", "Docker", "AWS", "CI/CD", "Terraform", "Python"],
        "interests": ["Cloud Architecture", "Site Reliability", "Automation"],
        "experience": 4,
        "projects": ["Infrastructure Automation", "Monitoring System", "Deployment Pipeline"],
        "desired_skills": ["Go", "Machine Learning Operations", "Cloud Security"],
        "manager_id": "manager456",
        "joined_date": "2021-01-10"
    },
    {
        "user_id": "user345",
        "name": "Taylor Williams",
        "email": "taylor.williams@company.com",
        "department": "Data Science",
        "role": "Data Scientist",
        "skills": ["Python", "Machine Learning", "SQL", "Data Visualization", "Statistics"],
        "interests": ["Deep Learning", "Natural Language Processing", "Computer Vision"],
        "experience": 3,
        "projects": ["Customer Segmentation", "Recommendation Engine", "Fraud Detection"],
        "desired_skills": ["MLOps", "Cloud Computing", "Big Data Technologies"],
        "manager_id": "manager789",
        "joined_date": "2022-05-20"
    },
    {
        "user_id": "user456",
        "name": "Morgan Lee",
        "email": "morgan.lee@company.com",
        "department": "Product",
        "role": "Product Manager",
        "skills": ["Product Strategy", "Agile", "User Research", "Analytics", "Market Analysis"],
        "interests": ["UX Design", "Growth Hacking", "AI Product Management"],
        "experience": 6,
        "projects": ["Mobile App Launch", "Enterprise Solution", "Customer Experience Redesign"],
        "desired_skills": ["Technical Product Management", "Data Science", "Leadership"],
        "manager_id": "manager999",
        "joined_date": "2019-11-05"
    },
    {
        "user_id": "user567",
        "name": "Casey Martinez",
        "email": "casey.martinez@company.com",
        "department": "Engineering",
        "role": "Frontend Engineer",
        "skills": ["React", "JavaScript", "CSS", "Responsive Design", "UI/UX", "Accessibility"],
        "interests": ["Web Performance", "Design Systems", "Interactive Visualizations"],
        "experience": 4,
        "projects": ["Design System Implementation", "Customer Portal UI", "Mobile Responsive Redesign"],
        "desired_skills": ["TypeScript", "React Native", "WebGL"],
        "manager_id": "manager456",
        "joined_date": "2021-03-15"
    },
    {
        "user_id": "user678",
        "name": "Riley Thompson",
        "email": "riley.thompson@company.com",
        "department": "Security",
        "role": "Security Engineer",
        "skills": ["Network Security", "Penetration Testing", "Security Auditing", "Python", "Risk Assessment"],
        "interests": ["Threat Intelligence", "Application Security", "Zero Trust Architecture"],
        "experience": 7,
        "projects": ["Security Operations Center", "Vulnerability Management Program", "Authentication System"],
        "desired_skills": ["Cloud Security", "Security Architecture", "Incident Response"],
        "manager_id": "manager222",
        "joined_date": "2018-06-10"
    },
    {
        "user_id": "user789",
        "name": "Jordan Patel",
        "email": "jordan.patel@company.com",
        "department": "Engineering",
        "role": "Backend Engineer",
        "skills": ["Java", "Spring Boot", "Microservices", "SQL", "NoSQL", "API Design"],
        "interests": ["System Design", "Distributed Systems", "Performance Optimization"],
        "experience": 5,
        "projects": ["Payment Processing Service", "User Authentication Service", "Data Processing Pipeline"],
        "desired_skills": ["Cloud Architecture", "Golang", "Event-Driven Architecture"],
        "manager_id": "manager456",
        "joined_date": "2020-02-12"
    },
    {
        "user_id": "user890",
        "name": "Quinn Nguyen",
        "email": "quinn.nguyen@company.com",
        "department": "UX Design",
        "role": "Senior UX Designer",
        "skills": ["User Research", "Wireframing", "Prototyping", "Usability Testing", "Visual Design"],
        "interests": ["Design Systems", "Accessibility", "Psychology of Design"],
        "experience": 6,
        "projects": ["Mobile App Redesign", "E-commerce UX Overhaul", "Design System"],
        "desired_skills": ["UX Writing", "Design Leadership", "Frontend Development"],
        "manager_id": "manager333",
        "joined_date": "2019-04-15"
    },
    {
        "user_id": "user901",
        "name": "Avery Wilson",
        "email": "avery.wilson@company.com",
        "department": "Data Engineering",
        "role": "Data Engineer",
        "skills": ["Python", "Spark", "SQL", "ETL", "Data Warehousing", "Airflow"],
        "interests": ["Stream Processing", "Data Architecture", "Real-time Analytics"],
        "experience": 4,
        "projects": ["Data Lake Implementation", "Real-time Analytics Pipeline", "Data Integration Platform"],
        "desired_skills": ["Cloud Data Solutions", "Machine Learning Engineering", "Distributed Systems"],
        "manager_id": "manager789",
        "joined_date": "2021-08-20"
    },
    {
        "user_id": "user012",
        "name": "Dakota Robinson",
        "email": "dakota.robinson@company.com",
        "department": "Engineering",
        "role": "QA Engineer",
        "skills": ["Automated Testing", "Test Planning", "Python", "Selenium", "API Testing", "Performance Testing"],
        "interests": ["Continuous Testing", "Test Automation Frameworks", "Quality Metrics"],
        "experience": 3,
        "projects": ["Test Automation Framework", "Mobile App Testing", "Performance Test Suite"],
        "desired_skills": ["DevOps", "Security Testing", "AI in Testing"],
        "manager_id": "manager456",
        "joined_date": "2022-01-10"
    }
]